import React from 'react'
import { CardMedia, Typography } from '@mui/material'
import { Box } from '@mui/system'
import axios from 'axios'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import LinearProgress from '@mui/material/LinearProgress';
import CircularProgress from '@mui/material/CircularProgress';

export default function Home() {
  const [value, setValue] = React.useState({
    p2p: 0,
    blueBuy: 0,
    blueSell: 0
  })

  function request() {
    axios.get('api/cripto')
      .then(value => {
        setValue({
          p2p: value.data.p2p,
          blueBuy: value.data.blueBuy,
          blueSell: value.data.blueSell
        })
      })
  }

  React.useEffect(() => {
    request()
    const cron = setInterval(request, 120000)
    return () => clearInterval(cron)
  }, [])

  if (value === 0) {
    return (
      <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100vh' }}>
        <CircularProgress />
      </Box>
    )
  }

  return (
    <div className={styles.container} style={{ backgroundColor: '#000', height: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', flexDirection: 'column', position: 'relative' }} >
      <Head>
        <title>Dolar Hoy!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'center', flexDirection: 'column' }}>
        <Typography component='h2' sx={{ fontFamily: 'Montserrat', fontWeight: 600, fontSize: '42px' }} >
          Valor promedio Binance P2P:<span style={{ color: '#FFAB00' }} > ${value.p2p}</span>
          <Typography sx={{ fontFamily: 'Montserrat', fontWeight: 200, fontSize: '12px' }} >Este valor es calculado con los primeros 20 precios de venta y de compra de USDT en Binance</Typography>
        </Typography>
        <Typography component='h2' sx={{ fontFamily: 'Montserrat', fontWeight: 600, fontSize: '42px' }} >
          Dolar blue compra:<span style={{ color: '#FFAB00' }} > ${value.blueBuy}</span>
        </Typography>
        <Typography component='h2' sx={{ fontFamily: 'Montserrat', fontWeight: 600, fontSize: '42px' }} >
          Dolar blue venta:<span style={{ color: '#FFAB00' }} > ${value.blueSell}</span>
        </Typography>
      </Box>
      <Box sx={{ display: 'flex', position: 'absolute', bottom: 100 }} >
        <Link href={'https://github.com/valenbenitez'} >
          <a target={'_blank'} >
            <CardMedia component='img' alt='BB-8' image='/icon-github.svg' sx={{ width: '60px' }} />
          </a>
        </Link>
        <Link href={'https://github.com/brayanobisto'} >
          <a target={'_blank'} >
            <CardMedia component='img' alt='BB-8' image='/icon-github.svg' sx={{ width: '60px' }} />
          </a>
        </Link>
      </Box>
    </div>
  )
}
